contextPath: /api/v1
database:
    url: jdbc:h2:file:~/devicecommands;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
    password:
mqtt:
  host: 192.168.1.136
  port: 1883
  id: zigbee
  username: zigbee
  password: zigbee
  topicFilter: zigbee2mqtt/


cache:
  caches:
    deviceCommands:
      expireAfterWrite: 1
      timeUnit: HOURS
      maximumSize: 1000
      recordStats: true
    deviceRules:
      expireAfterWrite: 1
      timeUnit: HOURS
      maximumSize: 100
      recordStats: true
      softValues: true
