contextPath: /api/v1
mqtt:
  host: 192.168.1.136
  port: 1883
  id: zigbee
  username: zigbee
  password: zigbee
  topicFilter: zigbee2mqtt/


cache:
  caches:
    deviceCommands:
      expireAfterWrite: 1
      timeUnit: HOURS
      maximumSize: 1000
      recordStats: true
    deviceCategories:
      expireAfterWrite: 30
      timeUnit: MINUTES
      maximumSize: 100
      recordStats: true
      softValues: true
    deviceModels:
      expireAfterWrite: 2
      timeUnit: HOURS
      maximumSize: 1000
      recordStats: true
      weakKeys: true
